language: python
python: "2.7"
before_install:
  - sudo apt-get install -y libjpeg-dev libgif-dev libpng-dev xpdf zlib1g-dev
  - pip install http://effbot.org/downloads/Imaging-1.1.7.tar.gz
install:
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -Nc travis.cfg
script: bin/test -s plone.app.imagecropping
